### ISSUE TITLE
'and', 'not' and 'or' are not colored

### ISSUE THREAD

**Issue by JasonMan34** [SuperiorServers/vscode-glua#1]
Not sure if intentional or not, but I think they should match the color of if/then/end/etc.

**Comment by aStonePenguin** [comment]
The default theme for some reason doesn't support that even with the lua support it ships with. Try [another theme](https://marketplace.visualstudio.com/search?target=VSCode&category=Themes&sortBy=Downloads) such as [mine](https://marketplace.visualstudio.com/items?itemName=aStonedPenguin.tomorrow-night-eighties-contrast).
